language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t burakunuvar/docker-react -f Dockerfile.dev

script:
- docker run -e CI=true burakunuvar/docker-react npm run test
