language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t burakunuvar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true burakunuvar/docker-react npm run test

#http://dockerreact-env.bba47kexay.eu-west-1.elasticbeanstalk.com/
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-158927923071"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
