# docker build .
# docker build -f Dockerfile.dev .
# use an existing docker image as a base

FROM node:alpine

# specify a working directory

WORKDIR '/app'

# to prevent unnecessary rebuilds
COPY ./package.json ./
RUN npm install
COPY ./ ./

# tell the image what to do when it starts as a container

CMD ["npm","run","start"]
